# -*- coding: utf-8 -*-
"""DTL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ANX364LzFeQdIOwN8suzVW63dxWBpAaO
"""

import os
import unicodedata
import pandas as pd

DATA_DIR = '/content'

def find_file(pattern, directory=DATA_DIR):
    target = unicodedata.normalize('NFC', pattern).casefold()
    matches = [
        name for name in os.listdir(directory)
        if target in unicodedata.normalize('NFC', name).casefold()
    ]
    if not matches:
        raise FileNotFoundError(
            f'Файл по шаблону "{pattern}" не найден. '
            f'Есть: {sorted(os.listdir(directory))}'
        )
    return os.path.join(directory, matches[0])

def read(pattern, **kwargs):
    path = find_file(pattern)
    print('Читаю:', path)
    return pd.read_csv(path, sep=',', **kwargs)

event_log_sample   = read('журнал_событий')
channels_directory = read('справочник_каналов')
objects_directory  = read('справочник_объектов')

journal_2019 = read('ext-journal-2019')
journal_2020 = read('ext-journal-2020')
journal_2023 = read('ext-journal-2023')
journal_2026 = read('ext-journal-2026')

display(event_log_sample.head())
display(event_log_sample.info())

display(channels_directory.head())
display(channels_directory.info())

display(objects_directory.head())
display(objects_directory.info())

display(journal_2019.head())
display(journal_2019.info())

display(journal_2020.head())
display(journal_2020.info())

display(journal_2023.head())
display(journal_2023.info())

display(journal_2026.head())
display(journal_2026.info())

import pandas as pd

# Собираем все годовые журналы в единый словарь или список
journals_dict = {
    '2019': journal_2019,
    '2020': journal_2020,
    '2023': journal_2023,
    '2026': journal_2026
}

# Добавляем колонку с годом для удобства и объединяем в один датафрейм
dfs = []
for year, df in journals_dict.items():
    temp_df = df.copy()
    temp_df['год'] = year
    dfs.append(temp_df)

df_all_journals = pd.concat(dfs, ignore_index=True)

# Проверяем результат
print(f"Общий объем записей: {len(df_all_journals):,}")
display(df_all_journals.head())

display(df_all_journals['значение_датчика'].value_counts(dropna=False))

"""
Выведем результаты исчисление (в целях экономии места удалим даты)"""

from datetime import datetime
import re
import pandas as pd

unique_vals = df_all_journals['значение_датчика'].dropna().unique()


def is_date(val):
  # 1. Проверка через встроенную конвертацию pandas (ловит почти любые типы дат и datetime)
  try:
    # Если строка/объект парсится в валидную дату — считаем датой
    pd.to_datetime(val)
    # Исключаем чистые числа, которые pandas может случайно попытаться распарсить
    if isinstance(val, (int, float)):
      return False
    # Исключаем строки, состоящие только из цифр (например, айдишники вроде "20231231")
    if str(val).isdigit():
      return False
    return True
  except (ValueError, TypeError):
    pass

  # 2. Дополнительные регулярные выражения для специфических текстовых форматов
  s = str(val).strip()
  date_patterns = [
      r'^\d{2}\.\d{2}\.\d{4}',  # 31.12.2023
      r'^\d{4}-\d{2}-\d{2}',  # 2023-12-31
      r'^\d{2}/\d{2}/\d{4}',  # 31/12/2023
      r'^\d{2}:\d{2}:\d{2}',  # 12:30:00
  ]

  for pattern in date_patterns:
    if re.match(pattern, s):
      return True

  return False


# Фильтрация
filtered_vals = [val for val in unique_vals if not is_date(val)]

print(f'Всего уникальных вариантов (без дат): {len(filtered_vals)}\n')

# Вывод результатов
for i, val in enumerate(filtered_vals, start=1):
  print(f'{i}|{val}')

import re
import numpy as np
import pandas as pd

# Трафарет для дат вида "02.04.2019 07:47:21" (с опциональным временем)
DATE_PATTERN = re.compile(r'^\d{2}\.\d{2}\.\d{4}( \d{2}:\d{2}:\d{2})?$')

def convert_sensor_types(df, source_col='значение_датчика'):
    """
    Классифицирует значение_датчика на числа / даты-артефакты / статусы.
    Исходный столбец source_col не изменяется - все результаты
    складываются в новые столбцы.
    """
    df = df.copy()
    raw = df[source_col].astype(str)

    is_date = raw.str.match(DATE_PATTERN)
    numeric = pd.to_numeric(raw, errors='coerce')
    is_numeric = numeric.notna() & ~is_date

    df['тип_значения'] = np.select(
        [is_date, is_numeric],
        ['date_artifact', 'numeric'],
        default='status'
    )

    df['значение_числовое'] = numeric.where(is_numeric)
    df['значение_dt'] = pd.to_datetime(raw.where(is_date), errors='coerce')
    df['значение_статус'] = raw.where(df['тип_значения'] == 'status').astype('category')

    print('Числовых:', is_numeric.sum())
    print('Дат-артефактов:', is_date.sum())
    print('Статусов:', (df['тип_значения'] == 'status').sum())

    return df

# Применяем к таблице
df_all_journals = convert_sensor_types(df_all_journals)

# Проверка результата
print(df_all_journals['тип_значения'].value_counts())
print()
print(df_all_journals.head(10))

df_all_journals['значение_обработанное'] = (
    df_all_journals['значение_числовое']
    .combine_first(df_all_journals['значение_dt'])
    .combine_first(df_all_journals['значение_статус'])
)

print(df_all_journals.head(10))

df_all_journals = df_all_journals.drop(
    columns=['тип_значения', 'значение_числовое', 'значение_dt', 'значение_статус']
)

print(df_all_journals.columns.tolist())
print(df_all_journals.head(10))

display(df_all_journals.info())

display(df_all_journals.head())

status_mapping = {
    # Исправление вариантов написания
    "Дв": "Да",
}

undefined_values = ["Неопределен", "Не определено", "nan", "None", ""]

df_all_journals["значение_нормализованное"] = (
    df_all_journals["значение_датчика"]
    .astype(str)
    .str.strip()
    .replace(status_mapping)
)

df_all_journals["значение_нормализованное"] = (
    df_all_journals["значение_нормализованное"]
    .replace(undefined_values, np.nan)
)

"""
for channel, group in df_all_journals.groupby('ид_канала_данных'):

    for index, row in group.iterrows():

        x = group[
            (group['дата'] >= row['дата'] - pd.Timedelta(days=30)) &
            (group['дата'] < row['дата'])
        ]['значение_обработанное']

        if len(x) < 2:
            continue

        median = x.median()
        std = x.std()

        deviation = abs(row['значение_обработанное'] - median) / std if std != 0 else 0

        if deviation > 3:
            df_all_journals.loc[index, 'flags'] = 'spike'

"""
FLAPPING_WINDOW = 12
FLAPPING_CHANGES = 6

for channel, group in df_all_journals.groupby('ид_канала_данных'):

    for index, row in group.iterrows():

        x = group[
            (group['дата'] >= row['дата'] - pd.Timedelta(days=30)) &
            (group['дата'] < row['дата'])
        ]['значение_датчика']

        if len(x) < FLAPPING_WINDOW:
            continue

        x = x.tail(FLAPPING_WINDOW)

        changes = (x != x.shift()).sum() - 1

        if changes >= FLAPPING_CHANGES:
            df_all_journals.loc[index, 'flags'] = 'flapping'

df_all_journals['дата'] = pd.to_datetime(
    df_all_journals['дата'],
    errors='coerce'
)


FLAPPING_WINDOW = 12
FLAPPING_CHANGES = 6

MIN_HISTORY = 30
INITIAL_WINDOW_DAYS = 30
WINDOW_STEP_DAYS = 30


KEY_STATUS_FLAGS = {
    "Обнаружен дым": "smoke",
    "Обнаружен газ": "gas",
    "Затоплен": "flood",
    "Неисправен": "fault",
    "Батарея разряжена": "battery_low",
    "Батарея неисправна": "battery_fault",
    "Обесточен": "power_off",
    "Рычаг сдернут": "lever_alarm",
    "Не замкнут": "contact_open",
}


for channel, group in df_all_journals.groupby('ид_канала_данных'):

    for index, row in group.iterrows():

        # 1. Ключевые аварийные состояния
        if row['значение_датчика'] in KEY_STATUS_FLAGS:

            df_all_journals.loc[index, 'flags'] = (
                KEY_STATUS_FLAGS[row['значение_датчика']]
            )

            continue

        # 2. Проверка числовых значений
        if (
            pd.notna(row['значение_обработанное'])
            and type(row['значение_обработанное']) in [int, float]
        ):

            # Все предыдущие числовые значения
            history = group[
                (group['дата'] < row['дата']) &
                (
                    group['значение_обработанное'].apply(
                        lambda v: type(v) in [int, float]
                    )
                )
            ]['значение_обработанное']

            # Первое числовое значение не проверяем
            if len(history) == 0:
                continue

            # Если истории меньше 31 значения,
            # берём ближайшие предыдущие значения
            if len(history) <= MIN_HISTORY:

                x = history.tail(MIN_HISTORY)

            else:

                # Начинаем с 30 дней
                window_days = INITIAL_WINDOW_DAYS

                while True:

                    x = group[
                        (group['дата'] >= row['дата'] - pd.Timedelta(days=window_days)) &
                        (group['дата'] < row['дата']) &
                        (
                            group['значение_обработанное'].apply(
                                lambda v: type(v) in [int, float]
                            )
                        )
                    ]['значение_обработанное']

                    # Если найдено больше 30 значений,
                    # используем это окно
                    if len(x) > MIN_HISTORY:
                        break

                    # Проверяем, дошли ли до самых ранних данных
                    earliest_date = group['дата'].min()

                    if (
                        pd.notna(earliest_date)
                        and row['дата'] - pd.Timedelta(days=window_days)
                        <= earliest_date
                    ):
                        break

                    # Расширяем окно ещё на 30 дней
                    window_days += WINDOW_STEP_DAYS

            # Проверяем только если есть история
            if len(x) > 0:

                median = x.median()
                std = x.std()

                if std != 0:

                    deviation = (
                        abs(row['значение_обработанное'] - median) / std
                    )

                else:

                    deviation = 0

                # Аномальное числовое значение
                if deviation > 3:

                    df_all_journals.loc[index, 'flags'] = 'spike'

        # 3. Проверка текстовых значений
        elif pd.notna(row['значение_датчика']):

            x = group[
                (group['дата'] >= row['дата'] - pd.Timedelta(days=30)) &
                (group['дата'] < row['дата'])
            ]['значение_датчика']

            if len(x) >= FLAPPING_WINDOW:

                x = x.tail(FLAPPING_WINDOW)

                changes = (x != x.shift()).sum() - 1

                if changes >= FLAPPING_CHANGES:

                    df_all_journals.loc[index, 'flags'] = 'flapping'